#pragma once

namespace PVTPackage
{
	enum class PVT_TYPE { BLACK_OIL = 0, DEAD = 0, GENERAL = 1, MODIFIED = 2, API_TRACKING = 3, COMPOSITIONAL = 4, UNKNOWN = -1};
	enum class COMPOSITIONAL_FLASH_TYPE { TRIVIAL = 0, WILSON_KVALUES = 1, TABULATED_KVALUES = 2, FREE_WATER_FLASH = 3, THREE_PHASE_FLASH = 4, UNKNOWN = -1 };
	enum class EOS_TYPE { REDLICH_KWONG_SOAVE = 1, PENG_ROBINSON = 0, UNKNOWN = -1 };
	enum class PHASE_TYPE { LIQUID_WATER_RICH = 2, OIL = 1, GAS = 0, UNKNOWN = -1 };

}
